version: "3.9"
services:
  backend:
    build: ./backend
    image: knosc_backend
    hostname: 127.0.0.1
    ports:
      - 5000:5000
  frontend:
    build: ./frontend
    image: knosc_frontend
    hostname: localhost
    ports:
      - 8080:80
